language: node_js
sudo: false
node_js:
- node
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
  code_climate: true
  browserstack: true
  sauce_connect: true
  jwt: # Sauce Labs
    secure: "glLJ0kkovazgIKqt5Hfh5pmWYE7ZHlGu8WuRsEjG+q5VNEOiKbETN/aiAccYIzwcrkEFuywIFAJfdIj21t7cBIb9R0YD15oZnV2QW6jMTRE61sFmigvLCJ6Q1Z15HM+KbgI9cxCfpSW2OIdQ4iLXiiB6FlLOrMl2CFtfb71N24ySizZ5N5lo/jPFxdvah6RIQ5O3NLivPyYegYHo7ckOuOi9qUgJ8lWh09pVGkn12RPOm+yfYHoD+SEUXuzoS7H55R9SCKh3bOPzuXyUcCt2p3lV5kdFEM6aJEcRlu2kp9yc5u8ht5jXRuk+DDRe2F6qo0wQQFKCRvfFjsHF9P/ix0tsBjLAP1a8VjY8oGWJn4siknLPRYu6FUzUQdFAQ+40MLieKtiwxxj5hQ1TJfiM8QlvhRU9oKkyoGsfb5EWXTpi/vx1OgUzppcN37+AGhYu8kvCCaTVMuT24PO7osfj9UXdaCP9XaG88cwt6KCgT3XjVLbh2ZBRtIow/bfHU17rHSUX4qoJnNpT2+hbxUr+xPU0GEEcdMhtoWF9u4vkAAW60Xyz95MMzB6HUEYyfCmjtAiYSBdIopBhe4+/PDtgOxDJ9e15eHLv2FpXD8TABy+wqPVRfusvsjKrG9sFfbL5ydXSQQPZYN4v6bPbSqdTjmcI2k9ia5mYca8AhginslY="
install:
- npm prune
- npm install
- npm update
script:
- npm run lint
- npm run build
- npm run test
- chmod +x ./scripts/link-npm.sh
- ./scripts/link-npm.sh
- chmod +x ./scripts/run-demo.sh
- ./scripts/run-demo.sh
- npm run test:e2e:browserstack
after_success:
- npm install -g codeclimate-test-reporter
- codeclimate-test-reporter < coverage/lcov/lcov.info
env:
  global:
  # CodeClimate
  - secure: FKZ9e8BDaR+Y8wrrkBLSi7JbPl6fm5Vk3LBvj7dydMsIXXoIgCF1Wd1uFDp0MkiwPGqi0cuKw/AfzM8h85FbHOMkVNYS3vO8Vc0vHWkc4rXqtEjjtceD0cFuhZzruSto5D8u2Ehc5o+6xLl48ycJJ68P+6941PchfXPEFYlRS2xQhmAHudjxmxaJgWd4qes3SyiAyZ3fkIHg84mOwPnX8mgXI74uo3sQ/bMghy3qQ5NZPvYRlrLr/qirVBOx0Yu2XLqDDZm/XdR9isnEwWmujJgRbbvZako4Zqg0b1W4vAlmPNu74NzaorZqaZHWsE0hPWY8Zur1pYaB5vKqzqR9xMFQYlZtbc73ts2q47rx106lyJsb5yz2cC4RfEh/0AqUDRfhtUBpI+yAFTWx/rUz9htiLFRhpi4g3lJpPsSx2mFkRyGrhv0XnnSfEp5IVEeazimRKDtIHm/r4t+Wna9Xz3XBvcoAIMzbwV7bcCbrAfisWdA+87001Qj2qTs6IC7VPzFonVhZrbpGkxPETE7c3X9MpF3OP5WAIyTzcViqykWUuFBXbbCDs95LmcBtUyP3ffuZqn4iuEdhMNf07bEWUiYec2U44m4K/zTUkNCI9wc/T3hzmKO7DO7gwOJ/P19v/pMthVz969HRuX1NEjZXm2DuBt3/2XrxH3yajhAl0EM=
  - BROWSERSTACK_USER=nathanmcgrath1
  - BROWSER_STACK_ACCESS_KEY=UdRqzqqrBufbTCQGqiK5
  - SAUCE_USERNAME=AmdCore
