language: node_js
node_js:
- node

env:
  global:
  - BROWSERSTACK_USERNAME=nathanmcgrath1
  - secure: DUiJH8ALOEo8NEcUNdQu+MpQL/YPMlazv37Tba1Rt4b6EAVwRugVQH2F15T65HmmFkzHVMm6R4t9BOBwReK0VJCkIBrgb/tCNNXcqcl5CDtueotiVZVK0xaxD7EPWaMh+sqh7ZFHPhMD21EuS6mKZ2LkQ1zaJYuJsaj1werNC4hETXE5klOcGdaIpVERfD+Helx90MRhSozuhOWh2SHVY+sSFmkXW3Zp5xn0ZR5fNviQAMrX9RU0QKWQIVh/mzxgujZTsojTcnNsWBOlyw6obeP94BuzfnJo0mhWc7aXsuTIDAIfRQbpyH/FkHiabtHA22aZ3rCDnYYA1ktEV56vbjDPQ65vAW9mWEcCSkD1P6AXxkYzLNB/LvaBGMEdY03Gv2SY9NKJNP5gcihnhIzFlK16soBeZpvRzEYGJneXOwEjfhIlZqT6IaRIIRTZg6QiGItruRDik+0bKwPl90LYDd2h4iklOTvz48FUJKeUjtZ+YNRDGLH+TNZ51nOmdXCKd4t/Hx0dzoawuDHJ/Z5P8EINKaZAmGIw6wR1q2He5fVRzkC6w8CbpNIN6NLH5ElS0uI4bLETok9fC4jSnpVj/eNe2XnSTtIaq/6RWTPxtpQirVONW32OmJPDuBx6Oe82uc+AM+VJFrqWCOg541nQqzKkPHUQHnb3s7HRX117pUw=
  - secure: lMcxaMqpUiHqSETuEUiOQTnuWL6frIZJw88ZXwMZLpgoBxj0wp30FuybCWVwSgschwskgZoADtx/llLKeFt4NOxSX+33ezhHOczRy1F7lwDobJ7BAk/GBkyLbE7NyLtdCCIhrjwS96bGdvCQwlAY9SDCEWP3zHQaln6TkeA2kxSYpnpo67BQmFXgiZzSsZmlDiEYh5B4eFbzMjFrzIGdeADHlsyKJYiSJWraEgAxXHOk3ijF/0xluH4sMjDSEDdX0v5eDmb17Hy3yZu/yx9uIIkPx901Y2WUn72xfaGp+C1Ww9uV1L9D2yVM6UnqO5b2afhI2nl3wTv+R2hT+aec7mtyDFetYtq74qfJ2+fdEqxni44PMyex26xxv5IyusET/Nfx42z2Zc+n1NWjrlJhvNXlNfJw1f0uUTWIGq/b4uLpUjPjvD2m0ZiKQk7rZ1EibpFE158dT2X6VHrZa6nk+PQLsuy2so6xeIvC3IbvCY0JYnJ/xR+A3Zn+XX3Hc7zW/IAKeDFRZRgyGlRfQkKzUYOIAoSZpyFLqMYvLJtVIMfPEuFiNARy0tcY/cXKEa2eBrszj7ojbA9NujkdyEf6KAEuTeAzru/jH/IqMoYVC8Mk0Yv4laYM1B6d8xCJOyKVK0qfqZeCt0/VfhWE8uZHVfrKb1ihL53T8PkbtjoQ9zo=

addons:
  code_climate:
    repo_token: "${CODECLIMATE_TOKEN}"
  browserstack:
    username: "${BROWSERSTACK_USERNAME}"
    access_key: "${BROWSERSTACK_ACCESS_KEY}"

install:
- npm prune
- npm install
- npm update

jobs:
  include:
  - stage: lint
    script: npm run lint
  - stage: build
    script: npm run build
  - stage: test
    script: npm run test
    after_success:
    - npm install -g codeclimate-test-reporter
    - codeclimate-test-reporter < coverage/lcov/lcov.info
  - stage: test:e2e
    script: npm run test:e2e:browserstack
