language: node_js
node_js:
- node
env:
  global:
  - BROWSERSTACK_USERNAME=nathanmcgrath1
  - secure: lMcxaMqpUiHqSETuEUiOQTnuWL6frIZJw88ZXwMZLpgoBxj0wp30FuybCWVwSgschwskgZoADtx/llLKeFt4NOxSX+33ezhHOczRy1F7lwDobJ7BAk/GBkyLbE7NyLtdCCIhrjwS96bGdvCQwlAY9SDCEWP3zHQaln6TkeA2kxSYpnpo67BQmFXgiZzSsZmlDiEYh5B4eFbzMjFrzIGdeADHlsyKJYiSJWraEgAxXHOk3ijF/0xluH4sMjDSEDdX0v5eDmb17Hy3yZu/yx9uIIkPx901Y2WUn72xfaGp+C1Ww9uV1L9D2yVM6UnqO5b2afhI2nl3wTv+R2hT+aec7mtyDFetYtq74qfJ2+fdEqxni44PMyex26xxv5IyusET/Nfx42z2Zc+n1NWjrlJhvNXlNfJw1f0uUTWIGq/b4uLpUjPjvD2m0ZiKQk7rZ1EibpFE158dT2X6VHrZa6nk+PQLsuy2so6xeIvC3IbvCY0JYnJ/xR+A3Zn+XX3Hc7zW/IAKeDFRZRgyGlRfQkKzUYOIAoSZpyFLqMYvLJtVIMfPEuFiNARy0tcY/cXKEa2eBrszj7ojbA9NujkdyEf6KAEuTeAzru/jH/IqMoYVC8Mk0Yv4laYM1B6d8xCJOyKVK0qfqZeCt0/VfhWE8uZHVfrKb1ihL53T8PkbtjoQ9zo=
  - secure: p7MKvU5K3sZdCkdL/lVjWBrgS9BcGPCZx2gUgJE4EXaEXQdq6MY1UF5OdM4KqqLg2+VdKoOap1BSulToXWEaMTPZ3cq2gnSVXWQMtx0/7V6Id/H/hl/WLfrh8SiHuH9v9el5QqnSSjtC4kDnA23s9jo6aTgjqsCxOUtro29u+TjXiy7qmqKuqhc6yiChwBjF7gWjHpENKHjTSm+hp2p0buStkP//e1WDAAT0df12YR8SyJ/q1K6Dx2+LYeFRRnDhKDO7vBUd7dbb4RF6KBbC5v6uKPBY6/1kuM+8wpXAkfmu1R5JFoyLPPJp6eEc/+lGcDUxL5fituTlkGd3bF074Zl25t6ynkA5JyN16mf0/JHLh9wcwF1kHqnTtg0FwIbYuH1TkP3LN3ZrjQrh3q32WP69eXd7qytjhUeFaz1BwHnj4vf0MMPv+SsbcCGHK9fQ47JFogekmz4itOLFiEWYJdt1cL+dFPkhWMaZbkdevH20lRZJs0zQoBWyIZAWOW6K40FeDZrl7UdMpj71Y7IMVx1te7O31c1kRtLnsTqB641r6M97izzWCzDAa93dgF0GKk65GplaqWCZGc04zsIiOLbuxGbynsEka/nbADgfoMxWizNavzGr3gq1Kf6wtrYp7nQgBEoU2M/oDkJtXVeDAmYE3HY7/EHJsrynw4ASD8I=
addons:
  code_climate:
    repo_token: $CODECLIMATE_TOKEN
  browserstack:
    username: $BROWSERSTACK_USERNAME
    access_key: $BROWSERSTACK_ACCESS_KEY
install:
- npm prune
- npm install
- npm update
jobs:
  include:
  - stage: lint
    script: npm run lint
  - stage: build
    script: npm run build
  - stage: test
    script: npm run test
    after_success:
    - npm install -g codeclimate-test-reporter
    - codeclimate-test-reporter < coverage/lcov/lcov.info
  - stage: test:e2e
    script: npm run test:e2e:browserstack
