language: node_js
node_js:
  - "node"

addons:
  code_climate:
    repo_token: ${CodeClimateToken}

install:
  - npm prune
  - npm install
  - npm update

jobs:
  include:
    - stage: lint
      script: npm run lint
    - stage: build
      script: npm run build
    - stage: test
      script: npm run test
      after_success:
        - npm install -g codeclimate-test-reporter
        - codeclimate-test-reporter < coverage/lcov/lcov.info