language: node_js
node_js:
- node
addons:
  code_climate: 
install:
- npm prune
- npm install
- npm update
script:
- npm run lint
- npm run build
- npm run test
after_success:
- npm install -g codeclimate-test-reporter
- codeclimate-test-reporter < coverage/lcov/lcov.info
env:
  global:
    secure: FKZ9e8BDaR+Y8wrrkBLSi7JbPl6fm5Vk3LBvj7dydMsIXXoIgCF1Wd1uFDp0MkiwPGqi0cuKw/AfzM8h85FbHOMkVNYS3vO8Vc0vHWkc4rXqtEjjtceD0cFuhZzruSto5D8u2Ehc5o+6xLl48ycJJ68P+6941PchfXPEFYlRS2xQhmAHudjxmxaJgWd4qes3SyiAyZ3fkIHg84mOwPnX8mgXI74uo3sQ/bMghy3qQ5NZPvYRlrLr/qirVBOx0Yu2XLqDDZm/XdR9isnEwWmujJgRbbvZako4Zqg0b1W4vAlmPNu74NzaorZqaZHWsE0hPWY8Zur1pYaB5vKqzqR9xMFQYlZtbc73ts2q47rx106lyJsb5yz2cC4RfEh/0AqUDRfhtUBpI+yAFTWx/rUz9htiLFRhpi4g3lJpPsSx2mFkRyGrhv0XnnSfEp5IVEeazimRKDtIHm/r4t+Wna9Xz3XBvcoAIMzbwV7bcCbrAfisWdA+87001Qj2qTs6IC7VPzFonVhZrbpGkxPETE7c3X9MpF3OP5WAIyTzcViqykWUuFBXbbCDs95LmcBtUyP3ffuZqn4iuEdhMNf07bEWUiYec2U44m4K/zTUkNCI9wc/T3hzmKO7DO7gwOJ/P19v/pMthVz969HRuX1NEjZXm2DuBt3/2XrxH3yajhAl0EM=
